version: '3.8'
networks:
  my-bridge:
    external:
      name: my-bridge
services:
  gray-avatar:
    build: .
    image: ixuewen/gray-avatar
    container_name: gray-avatar-docker
    restart: always
    networks:
      - my-bridge
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PORT=${GRAY_AVATAR_PORT}
      - CONTEXT_PATH=${GRAY_AVATAR_CONTEXT_PATH}
      - CORS_ORIGIN=${GRAY_AVATAR_CORS_ORIGIN}
